spring:
  ldap:
    base: dc=infor,dc=com
    embedded:
      validation:
        enabled: false #validation.enabled must set to false, otherwise it will validate AD schema. If so,  objectClass: user and sAMAccountName:admin will be not allowed in ldif file.
      base-dn: dc=infor,dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8389
      urls: ldap://localhost:8389/
