spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=yes&characterEncoding=utf-8
#    username: root
#    password: Passw0rd
    dynamic:
      primary: admin #设置默认的数据源或者数据源组,默认值即为admin
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      druid:
        stat-view-servlet:
        loginUsername: root
        loginPassword: enhantec@passw0rd
        initial-size: 1
        max-active: 20
        min-idle: 3
        max-wait: 1000
        validation-query: SELECT 1
      datasource:
#########Mysql
        admin:
          url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=yes&characterEncoding=utf-8
          orgUrlTemplate: jdbc:mysql://127.0.0.1:3306/%s?useUnicode=yes&characterEncoding=utf-8
          username: root
          password: Passw0rd
          driver-class-name: com.mysql.cj.jdbc.Driver
#########SQLServer
#        admin:
#            url: jdbc:sqlserver://192.168.4.253;databaseName=EHTEST
#            orgUrlTemplate: jdbc:sqlserver://192.168.4.253;databaseName=EHTEST
#            username: admin
#            password: Passw0rd
#            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    format:
      date-time: iso
    pathmatch:
      matching-strategy: ant_path_matcher #add this config to resolve the starting issue caused by Swagger
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        type:
          descriptor:
            sql: trace
  error:
    include-binding-errors: always #return detail error for rest service
  messages:
    #Must provide file messages.properties, otherwise messages config will not take effect
    basename: i18n/messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  profiles:
    active: dev
enhantec:
  common:
    security:
      passwordExpiredDays: 60
      authTypes: basic,ldap
      jwt:
        base64Secret: 'YmJlMWVmMjYxODM1ZGVkMWI2MzA5M2UxOGJmMmEzMTYzYTg4ZDk3MTJkYjA1Mzc3YTI3YThlYjBhN2I3YTdlZjk1MThiMmMzYjE5NjYzMWFjYjdlMDZmODlhMDdhNDg3NGRjODg5ZWJlODg5NjYzNzljNDQ0MzllYjYwN2U5ODE='
        tokenValidityInSeconds: 300

#    web:
#    validationCode:
#      image:
#        length: 6
#        width: 100
#        url: /user/*  #test validationCode filter by urls
server:
  port: ${SERVER_PORT:9000}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE
    com.enhantec: DEBUG
    sql: DEBUG
    #org.springframework.web: "debug"
mybatis-plus:
  type-handlers-package: com.enhantec.framework.config.typeHander
  global-config:
    #字段策略 0:"忽略判断,如果字段为NULL则直接更新为null,需要每次传入的实体对象为完整数据",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 0
    db-config:
      id-type: assign_id
#  mapper-locations: classpath*:com/enhantec/**/mapper/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    #Mybatis自动扫描到自定义的POJO，以用于MAPPER XML文件中的resultType
  type-aliases-package: com.enhantec.framework.security.common.model,com.enhantec.framework.scheduler.common.model,com.enhantec.wms.inbound.model