spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=yes&characterEncoding=utf-8
    username: root
    password: Passw0rd
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    format:
      date-time: iso
    pathmatch:
      matching-strategy: ant_path_matcher #add this config to resolve the starting issue caused by Swagger
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        type:
          descriptor:
            sql: trace
  error:
    include-binding-errors: always #return detail error for rest service
  profiles:
    active: dev

enhantec:
  common:
    security:
      authTypes: basic,ldap
      jwt:
        base64Secret: 'YmJlMWVmMjYxODM1ZGVkMWI2MzA5M2UxOGJmMmEzMTYzYTg4ZDk3MTJkYjA1Mzc3YTI3YThlYjBhN2I3YTdlZjk1MThiMmMzYjE5NjYzMWFjYjdlMDZmODlhMDdhNDg3NGRjODg5ZWJlODg5NjYzNzljNDQ0MzllYjYwN2U5ODE='
        tokenValidityInSeconds: 600

#    web:
#    validationCode:
#      image:
#        length: 6
#        width: 100
#        url: /user/*  #test validationCode filter by urls
server:
  port: ${SERVER_PORT:8060}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE
    com.enhantec: DEBUG
    sql: DEBUG
    #org.springframework.web: "debug"
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl